"""Markdown 转 HTML 渲染模块

- 将 push/notify 的 markdown 正文渲染为带样式的完整 HTML 页面
- 将 fetch 数据的"实体洞察"渲染为折叠分组的每日报告（AI Daily 实体洞察日报）
"""
import html
from typing import Dict, List

import markdown

__all__ = [
    "md_to_html_page",
    "generate_html_file",
    "render_entity_report",
    "save_entity_report",
]


def _build_page(title: str, body_html: str, footer_note: str = "") -> str:
    """把 markdown 转换后的 body_html 包进完整 HTML 页面（内嵌样式）"""
    escaped_title = html.escape(title or "AI Daily")
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{escaped_title}</title>
<style>
  :root {{
    --bg: #f7f8fa;
    --card: #ffffff;
    --text: #24292f;
    --muted: #6a737d;
    --accent: #2f6feb;
    --border: #e4e6eb;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
      "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
    line-height: 1.7;
  }}
  .page {{ max-width: 860px; margin: 0 auto; padding: 32px 20px 64px; }}
  .header {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 24px 28px;
    margin-bottom: 24px;
  }}
  .header h1 {{ margin: 0 0 8px; font-size: 26px; }}
  .header .meta {{ color: var(--muted); font-size: 14px; }}
  .content {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 28px 32px;
  }}
  .content h2 {{
    font-size: 20px;
    margin: 28px 0 12px;
    padding-bottom: 8px;
    border-bottom: 2px solid var(--border);
  }}
  .content h2:first-child {{ margin-top: 0; }}
  .content h3 {{ font-size: 17px; margin: 20px 0 8px; }}
  .content a {{ color: var(--accent); text-decoration: none; }}
  .content a:hover {{ text-decoration: underline; }}
  .content blockquote {{
    margin: 12px 0;
    padding: 4px 16px;
    border-left: 4px solid var(--accent);
    background: #f0f4ff;
    color: var(--muted);
  }}
  .content code {{
    background: #f0f2f5;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 0.9em;
  }}
  .content pre {{
    background: #24292f;
    color: #e6edf3;
    padding: 16px;
    border-radius: 8px;
    overflow-x: auto;
  }}
  .content pre code {{ background: transparent; padding: 0; }}
  .content hr {{ border: none; border-top: 1px solid var(--border); margin: 24px 0; }}
  .content img {{ max-width: 100%; border-radius: 8px; }}
  .footer {{ color: var(--muted); font-size: 13px; text-align: center; margin-top: 24px; }}
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <h1>{escaped_title}</h1>
    <div class="meta">{html.escape(footer_note)}</div>
  </div>
  <div class="content">
{body_html}
  </div>
  <div class="footer">Generated by AI Daily</div>
</div>
</body>
</html>
"""


def md_to_html_page(
    title: str, md_body: str, footer_note: str = ""
) -> str:
    """把 markdown 正文渲染为完整 HTML 页面。

    Args:
        title: 页面标题（放入 <title> 和页头）
        md_body: markdown 正文（不含 frontmatter）
        footer_note: 页头副标题/日期等说明文字
    """
    body_html = markdown.markdown(
        md_body,
        extensions=["extra", "tables", "fenced_code", "sane_lists"],
    )
    # markdown 输出的段落已带缩进,统一规范化缩进
    body_html = "\n".join(line.strip() for line in body_html.splitlines())
    return _build_page(title, body_html, footer_note)


def generate_html_file(md_filepath: str, title: str, footer_note: str = "") -> str:
    """读取 .md 文件（自动剥离 YAML frontmatter），生成同名 .html 文件。

    Args:
        md_filepath: markdown 文件路径（.md）
        title: 页面标题
        footer_note: 页头副标题

    Returns:
        生成的 .html 文件路径；md 不存在或为空时返回空字符串。
    """
    from pathlib import Path

    from src.markdown_utils import parse_frontmatter

    md_path = Path(md_filepath)
    if not md_path.exists():
        return ""

    text = md_path.read_text(encoding="utf-8")
    _, body = parse_frontmatter(text)
    if not body.strip():
        return ""

    html_path = md_path.with_suffix(".html")
    html_page = md_to_html_page(title, body, footer_note)
    html_path.write_text(html_page, encoding="utf-8")
    return str(html_path)


# ============ 实体洞察日报 ============

_ENTITY_CSS = """
<style>
  :root {
    --bg: #121212;
    --card: #1a1a1a;
    --text: #e0e0e0;
    --muted: #888888;
    --border: #2a2a2a;
    --act: #c4ed1a;
    --try: #b87aff;
    --watch: #4f6dff;
    --skip: #777777;
    --blue: #4f6dff;
    --gold: #c4ed1a;
    --serif: Georgia, "Times New Roman", "Songti SC", "SimSun", "Noto Serif SC", serif;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
      "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
    line-height: 1.7;
  }
  .page { max-width: 1120px; margin: 0 auto; padding: 0 16px; display: flex; gap: 24px; align-items: flex-start; }

  /* 左侧固定导航 */
  .sidebar {
    position: sticky;
    top: 0;
    flex-shrink: 0;
    width: 208px;
    height: 100vh;
    padding: 28px 8px 24px;
    box-sizing: border-box;
    overflow-y: auto;
  }
  .brand {
    font-family: var(--serif);
    font-size: 19px;
    font-weight: 800;
    color: #fff;
    padding: 0 12px 4px;
    letter-spacing: .5px;
  }
  .brand .brand-sub { display: block; font-family: inherit; font-size: 12px; font-weight: 500; color: var(--muted); margin-top: 3px; letter-spacing: 1px; }

  .main { flex: 1; min-width: 0; padding-top: 24px; padding-bottom: 64px; }

  /* 科技页头：深海蓝 + 渐变光晕顶线 */
  .hero {
    position: relative;
    background: linear-gradient(150deg, #121d33 0%, #0e1526 55%, #111b2e 100%);
    color: var(--text);
    border: 1px solid #223053;
    border-radius: 14px;
    padding: 30px 34px 26px;
    margin-bottom: 22px;
    box-shadow: 0 12px 36px rgba(4, 8, 18, .55);
    overflow: hidden;
  }
  .hero::before {
    content: "";
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
    background: linear-gradient(90deg, #4f6dff, rgba(79,109,255,.15) 70%, transparent);
  }
  /* 右上角电光蓝光晕（屏幕反射质感） */
  .hero::after {
    content: "";
    position: absolute;
    top: -60px; right: -60px;
    width: 260px; height: 260px;
    border-radius: 50%;
    background: radial-gradient(circle, rgba(23,61,255,.08) 0%, rgba(23,61,255,0) 70%);
    pointer-events: none;
  }
  .hero h1 { margin: 0 0 8px; font-family: var(--serif); font-size: 27px; font-weight: 800; letter-spacing: 1px; color: #fff; }
  .hero h1 .hl { color: #4f6dff; text-shadow: 0 0 14px rgba(79,109,255,.5); }
  .hero .meta { color: #888888; font-size: 13.5px; letter-spacing: .5px; }
  .hero .advice-line { color: var(--muted); font-size: 13px; margin-top: 8px; }
  .stats { display: flex; gap: 10px; margin-top: 18px; flex-wrap: wrap; }
  .stat {
    background: rgba(255,255,255,.04);
    border: 1px solid rgba(255,255,255,.1);
    border-radius: 20px;
    padding: 5px 15px;
    font-size: 13px;
    color: #b9c5da;
  }
  .stat b { font-size: 15px; color: #c4ed1a; margin-right: 4px; text-shadow: 0 0 10px rgba(196,237,26,.45); }

  /* 卡片 */
  .card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 24px;
    margin-top: 14px;
    scroll-margin-top: 18px;
    transition: box-shadow .18s, border-color .18s;
  }
  .card:hover { box-shadow: 0 10px 28px rgba(0, 0, 0, .45); border-color: rgba(79,109,255,.45); }
  .card-top { display: flex; align-items: flex-start; gap: 12px; }
  /* 评分：核心数字，黄绿强调（描边，无实底） */
  .score {
    flex-shrink: 0;
    min-width: 44px;
    height: 30px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 8px;
    padding: 0 10px;
    font-weight: 800;
    font-size: 15px;
    margin-top: 2px;
    color: #c4ed1a;
    border: 1px solid rgba(196,237,26,.45);
    background: transparent;
    box-shadow: 0 0 12px rgba(196,237,26,.10);
  }
  .card h3 { margin: 0; font-family: var(--serif); font-size: 16px; font-weight: 700; line-height: 1.55; flex: 1; }
  .card h3 a { color: var(--text); text-decoration: none; }
  .card h3 a:hover { color: #8fa6ff; text-decoration: underline; }
  .meta-line {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px;
    margin: 14px 0 0;
    color: var(--muted);
    font-size: 12.5px;
  }
  /* 标签统一：描边样式，20px 高，4px 圆角；蓝=场景 紫=状态 黄=门槛 */
  .industry, .alternative, .badge {
    display: inline-flex;
    align-items: center;
    height: 20px;
    padding: 0 8px;
    font-size: 12px;
    border-radius: 4px;
    background: transparent;
    white-space: nowrap;
  }
  .industry {
    border: 1px solid rgba(79,109,255,.5);
    color: #8fa6ff;
    font-weight: 500;
  }
  .alternative {
    border: 1px solid rgba(79,109,255,.45);
    color: #8fa6ff;
    font-weight: 500;
  }
  .badge.maturity {
    border: 1px solid rgba(184,122,255,.5);
    color: #d8c4f5;
  }
  .badge.effort {
    border: 1px solid rgba(196,237,26,.4);
    color: #c4ed1a;
  }
  .badge.advice {
    margin-left: auto;
    font-weight: 600;
  }
  .badge.advice.act { border: 1px solid rgba(196,237,26,.5); color: #c4ed1a; }
  .badge.advice.try { border: 1px solid rgba(184,122,255,.5); color: #d8c4f5; }
  .badge.advice.watch { border: 1px solid rgba(79,109,255,.55); color: #8fa6ff; }
  .badge.advice.skip { border: 1px solid rgba(119,119,119,.5); color: #9a9a9a; }

  /* 实体洞察：核心价值区，左侧 3px 黄绿渐变竖线 */
  .insight {
    margin-top: 16px;
    background: transparent;
    border: 1px solid rgba(196,237,26,.18);
    border-radius: 10px;
    padding: 18px 22px 18px 24px;
    font-size: 14px;
    color: #e0e0e0;
    position: relative;
  }
  .insight::before {
    content: "";
    position: absolute;
    left: 0; top: 0; bottom: 0;
    width: 3px;
    border-radius: 3px 0 0 3px;
    background: linear-gradient(180deg, #c4ed1a, rgba(196,237,26,0));
  }
  .insight .label {
    display: block;
    font-weight: 800;
    color: #c4ed1a;
    font-size: 13px;
    margin-bottom: 6px;
    letter-spacing: .5px;
  }

  /* 摘要：弱化的小字 */
  .summary {
    margin-top: 10px;
    color: var(--muted);
    font-size: 13px;
    line-height: 1.6;
    border-top: 1px dashed var(--border);
    padding-top: 8px;
  }

  /* 推演区块 */
  .deduce {
    margin-top: 12px;
    background: transparent;
    border: 1px solid var(--border);
    border-radius: 10px;
    overflow: hidden;
  }
  .deduce summary {
    cursor: pointer;
    list-style: none;
    padding: 12px 16px;
    font-size: 13.5px;
    font-weight: 700;
    color: #d0d0d0;
    background: rgba(255,255,255,.04);
    user-select: none;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .deduce summary::-webkit-details-marker { display: none; }
  .deduce summary:hover { background: rgba(255,255,255,.07); }
  .deduce .d-arrow { margin-left: auto; color: var(--muted); font-size: 11px; transition: transform .2s; }
  .deduce[open] .d-arrow { transform: rotate(180deg); }
  .deduce .d-body { padding: 20px 24px; border-top: 1px solid var(--border); }
  .deduce .d-step { margin-bottom: 20px; }
  .deduce .d-step:last-child { margin-bottom: 0; }
  .deduce .d-step-title {
    font-size: 13px;
    font-weight: 800;
    color: #ffffff;
    margin-bottom: 6px;
  }
  .deduce .d-step p { margin: 0; font-size: 13.5px; color: #c8c8c8; line-height: 1.75; }
  .deduce .d-signal {
    display: inline-block;
    border: 1px solid rgba(196,237,26,.45);
    color: #c4ed1a;
    border-radius: 4px;
    padding: 1px 8px;
    font-size: 12px;
    font-weight: 700;
    margin-bottom: 8px;
  }
  /* 行业排序条目：去背景，加粗标题 + 间距分段 */
  .deduce .d-map-item {
    margin: 0 0 16px;
    font-size: 13px;
    background: transparent;
    border: none;
    padding: 0;
  }
  .deduce .d-map-item:last-child { margin-bottom: 0; }
  .deduce .d-map-item b { color: #fff; font-weight: 700; display: block; margin-bottom: 3px; }
  .deduce .d-map-item .d-sense { color: #8fa6ff; font-weight: 700; margin-left: 8px; }
  .deduce .d-map-item div { color: #c8c8c8; }
  .deduce .d-card {
    background: transparent;
    border: none;
    padding: 0;
  }
  .deduce .d-card p { margin: 0 0 8px; font-size: 13px; color: #c8c8c8; }
  .deduce .d-card p:last-child { margin-bottom: 0; }
  .deduce .d-card b { color: #c4ed1a; }
  /* 顾问备忘录：独立悬浮卡片，黄绿外发光 */
  .deduce .d-kaifeng {
    margin-top: 18px;
    padding: 16px 18px;
    background: #1f1f1f;
    border: 1px solid rgba(196,237,26,.25);
    border-radius: 10px;
    box-shadow: 0 0 12px rgba(196,237,26,.20);
    font-size: 15px;
    font-weight: 600;
    color: #c4ed1a;
  }

  .empty { color: var(--muted); padding: 24px; text-align: center; }
  .footer { color: var(--muted); font-size: 13px; text-align: center; margin-top: 28px; }

  /* 分类导航（左侧竖向） */
  .cat-nav { display: flex; flex-direction: column; gap: 4px; margin-top: 20px; }
  .cat-chip {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 9px 12px;
    border-radius: 8px;
    background: transparent;
    border: 1px solid transparent;
    border-left: 3px solid transparent;
    color: #666666;
    font-size: 13.5px;
    text-decoration: none;
    transition: all .15s;
  }
  .cat-chip:hover { background: rgba(255,255,255,.04); color: #cccccc; }
  .cat-chip.active {
    border-left-color: #4f6dff;
    background: rgba(79,109,255,.10);
    color: #ffffff;
    font-weight: 700;
  }
  .cat-chip .cat-n {
    color: #888888;
    background: rgba(255,255,255,.08);
    border-radius: 20px;
    padding: 0 8px;
    font-size: 12px;
    font-weight: 600;
    min-width: 22px;
    text-align: center;
  }
  .cat-chip.active .cat-n { color: #c4ed1a; background: rgba(196,237,26,.1); }

  /* 行动分级导航（左侧竖向，分级色左竖线） */
  .adv-nav { display: flex; flex-direction: column; gap: 4px; margin-top: 14px; padding-top: 14px; border-top: 1px solid var(--border); }
  .adv-label { color: #666666; font-size: 11px; letter-spacing: 1.5px; padding: 0 12px 4px; }
  .adv-chip {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 12px;
    border-radius: 8px;
    background: transparent;
    border: 1px solid transparent;
    border-left: 3px solid transparent;
    color: #666666;
    font-size: 13px;
    text-decoration: none;
    transition: all .15s;
  }
  .adv-chip:hover { background: rgba(255,255,255,.04); color: #cccccc; }
  .adv-chip.act { border-left-color: rgba(196,237,26,.6); }
  .adv-chip.try { border-left-color: rgba(184,122,255,.6); }
  .adv-chip.watch { border-left-color: rgba(79,109,255,.7); }
  .adv-chip.skip { border-left-color: rgba(119,119,119,.6); }
  .adv-chip.active { background: rgba(255,255,255,.06); color: #ffffff; font-weight: 700; }
  .adv-chip .adv-n {
    color: #888888;
    background: rgba(255,255,255,.08);
    border-radius: 20px;
    padding: 0 8px;
    font-size: 12px;
    font-weight: 600;
    min-width: 22px;
    text-align: center;
  }
  .adv-chip.act .adv-n { color: #c4ed1a; background: rgba(196,237,26,.1); }
  .adv-chip.try .adv-n { color: #d8c4f5; background: rgba(184,122,255,.12); }
  .adv-chip.watch .adv-n { color: #8fa6ff; background: rgba(79,109,255,.12); }
  .adv-chip.skip .adv-n { color: #9a9a9a; background: rgba(119,119,119,.1); }
  .adv-chip.active .adv-n { background: rgba(255,255,255,.16); }

  .cat-group { margin-bottom: 6px; scroll-margin-top: 16px; }
  .cat-title {
    font-family: var(--serif);
    font-size: 20px;
    font-weight: 800;
    margin: 30px 0 14px;
    padding-left: 12px;
    border-left: 3px solid #4f6dff;
    color: #ffffff;
  }
  .cat-title .cat-count { color: var(--muted); font-size: 13px; font-weight: 400; margin-left: 8px; }
  .cat-title .cat-desc { color: var(--muted); font-size: 12px; font-weight: 400; margin-left: 6px; }
  .advice-line { color: var(--muted); font-size: 13px; margin-top: 6px; }

  /* 联系方式（深色 hero） */
  .contact { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; font-size: 13.5px; }
  .contact a, .contact .copy-wx {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 14px;
    border-radius: 20px;
    font-size: 13px;
    text-decoration: none;
  }
  .contact a {
    border: 1px solid rgba(196,237,26,.5);
    color: #c4ed1a;
  }
  .contact a:hover { background: rgba(196,237,26,.1); color: #d8f25a; }
  .contact .copy-wx {
    background: transparent;
    border: 1px dashed rgba(119,119,119,.6);
    color: #e0e0e0;
    cursor: pointer;
    user-select: none;
  }
  .contact .copy-wx:hover { background: rgba(255,255,255,.06); }
  .contact .copy-wx .tip { color: #888888; font-size: 12px; }

  /* 移动端：侧栏变顶栏 */
  @media (max-width: 860px) {
    .page { flex-direction: column; gap: 0; }
    .sidebar {
      position: sticky;
      top: 0;
      width: 100%;
      height: auto;
      padding: 12px 4px 10px;
      background: var(--bg);
      z-index: 10;
      border-bottom: 1px solid var(--border);
    }
    .brand { display: none; }
    .cat-nav { flex-direction: row; overflow-x: auto; margin-top: 0; padding-bottom: 4px; }
    .cat-chip { flex-shrink: 0; background: var(--card); border-color: var(--border); }
    .main { padding-top: 8px; }
  }
</style>
"""

# 行动建议 → (标题, 说明, 样式类, 是否默认展开)
_ADVICE_ORDER = ("立即行动", "小成本试用", "观望", "暂不跟进")
_ADVICE_META = {
    "立即行动": ("🔥 立即行动", "成熟、低门槛、强相关，现在就能用起来", "act", True),
    "小成本试用": ("✅ 小成本试用", "可低成本试错，验证是否适合自己", "try", True),
    "观望": ("👀 观望", "有前景但不成熟 / 门槛高 / 本地不适配，先跟踪", "watch", False),
    "暂不跟进": ("⛔ 暂不跟进", "与本地实体无关 / 概念太远 / 成本过高", "skip", False),
}

# AI 能力类型主分类 → (导航标题, 一句说明)
_CATEGORY_ORDER = (
    "视频生成",
    "图像生成",
    "智能体与自动化",
    "文本与内容",
    "大模型与API",
    "平台与商业模式",
    "政策与宏观",
    "其他",
)
_CATEGORY_META = {
    "视频生成": ("🎬 视频生成", "AI视频 / 剪辑 / 数字人 / 口播"),
    "图像生成": ("🖼️ 图像生成", "AI生图 / 商品图 / 图片编辑 / 设计"),
    "智能体与自动化": ("🤖 智能体与自动化", "AI同事 / 数字员工 / Agent / 自动化"),
    "文本与内容": ("✍️ 文本与内容", "文案 / 对话 / PPT / 知识整理"),
    "大模型与API": ("🧠 大模型与API", "模型发布 / 开源 / API降价 / 云能力"),
    "平台与商业模式": ("🏪 平台与商业模式", "大厂动态 / 收费 / 广告 / 流量入口"),
    "政策与宏观": ("🏛️ 政策与宏观", "政策 / 行业报告 / 投融资"),
    "其他": ("📦 其他", ""),
}
_ADVICE_CLS = {"立即行动": "act", "小成本试用": "try", "观望": "watch", "暂不跟进": "skip"}
_ADVICE_EMOJI = {"act": "🔥", "try": "✅", "watch": "👀", "skip": "⛔"}


def _deduce_card_html(d: Dict) -> str:
    """渲染顾问行动卡片（motive/industry_impact/feasibility/ecosystem + card 判断/决策/备忘录）"""
    def esc(v):
        return html.escape(str(v)) if v else ""

    # 兼容中英文键名变体
    def get(dd, *keys, default=""):
        for k in keys:
            v = dd.get(k)
            if v:
                return v
        return default

    card = d.get("card") or {}
    if not isinstance(card, dict):
        card = {}

    motive = esc(get(d, "motive", "动机分析"))
    ecosystem = esc(get(d, "ecosystem", "生态位冲击"))

    # 影响行业排序（兼容列表/字符串、中英文字段）
    impacts = d.get("industry_impact") or d.get("impact") or []
    impact_html = ""
    if isinstance(impacts, list) and impacts:
        parts = []
        for i, m in enumerate(impacts, 1):
            if not isinstance(m, dict):
                continue
            ind = get(m, "industry", "name", "行业")
            reason = get(m, "reason", "note", "说明", "理由")
            parts.append(
                f'<div class="d-map-item"><b>{i}. {esc(ind)}</b>'
                f"<div>{esc(reason)}</div></div>"
            )
        if parts:
            impact_html = "\n".join(parts)
    elif impacts:
        impact_html = f"<p>{esc(impacts)}</p>"

    # 落地可行性研判（四维度）
    feas = d.get("feasibility") or d.get("feasible") or {}
    feas_html = ""
    if isinstance(feas, dict):
        rows = [
            ("💰 成本门槛", get(feas, "cost", "cost_gate", "成本门槛", "成本")),
            ("🧑 消费习惯匹配度", get(feas, "habit", "消费习惯", "习惯")),
            ("🏗️ 基础设施依赖", get(feas, "infrastructure", "基础设施")),
            ("⚖️ 政策与平台风险", get(feas, "policy", "政策风险", "风险")),
        ]
        parts = [f"<p><b>{t}</b>：{esc(v)}</p>" for t, v in rows if v]
        if parts:
            feas_html = "\n".join(parts)

    judgement = esc(get(card, "judgement", "一句话核心判断", "核心判断"))
    decision = esc(
        get(card, "decision", "对老板的一句话决策建议", "一句话决策建议", "summary", "开封话总结", "决策建议")
    )
    memo = esc(get(card, "memo", "顾问备忘录", "备忘录", "总结"))

    def step(title, body):
        return (
            f'<div class="d-step"><div class="d-step-title">{title}</div>'
            f"{body}</div>"
            if body
            else ""
        )

    return f"""
<details class="deduce">
<summary>📇 顾问行动卡片<span class="d-arrow">▼</span></summary>
<div class="d-body">
  {step("🕵️ 动机分析", f"<p>{motive}</p>")}
  {step("📊 影响行业排序", impact_html)}
  {step("🔧 落地可行性研判", feas_html)}
  {step("⚔️ 生态位冲击", f"<p>{ecosystem}</p>")}
  {step("🎯 一句话核心判断", f"<p>{judgement}</p>")}
  {step("🗣️ 一句话决策建议", f"<p>{decision}</p>")}
  <div class="d-kaifeng">📝 顾问备忘录：{memo}</div>
</div>
</details>
"""


def _deduce_legacy_html(d: Dict) -> str:
    """渲染旧版五步推演为可折叠区块（兼容历史数据）"""
    def esc(v):
        return html.escape(str(v)) if v else ""

    signal_type = esc(d.get("signal_type"))
    signal = esc(d.get("signal"))
    evidence = esc(d.get("signal_evidence"))
    top_industry = esc(d.get("top_industry"))
    quadrant = esc(d.get("quadrant"))

    # 领域映射（兼容中英文字段名与常见变体）
    map_items = d.get("industry_map") or []
    map_html = ""
    if isinstance(map_items, list):
        parts = []
        for m in map_items:
            if not isinstance(m, dict):
                continue
            area = (
                m.get("area")
                or m.get("domain")
                or m.get("name")
                or m.get("industry")
                or m.get("field")
                or m.get("领域名")
                or ""
            )
            sense = (
                m.get("sense")
                or m.get("sensitivity")
                or m.get("敏感度")
                or ""
            )
            note = (
                m.get("note")
                or m.get("insight")
                or m.get("desc")
                or m.get("logic")
                or m.get("deduction")
                or m.get("推演")
                or m.get("一句推演")
                or ""
            )
            parts.append(
                f'<div class="d-map-item"><b>{esc(area)}</b>'
                f'<span class="d-sense">{esc(sense)}</span>'
                f'<div>{esc(note)}</div></div>'
            )
        map_html = "\n".join(parts)

    # 落地阶梯
    stairs = d.get("staircase") or []
    stairs_html = ""
    if isinstance(stairs, list):
        parts = []
        for i, s in enumerate(stairs, 1):
            if not isinstance(s, dict):
                continue
            parts.append(
                f'<p><b>阶段{i}（{esc(s.get("stage"))}）</b>：'
                f"{esc(s.get('action'))}</p>"
            )
        stairs_html = "\n".join(parts)

    card = d.get("action_card") or {}
    card_html = ""
    if isinstance(card, dict):
        card_html = (
            f'<div class="d-card">'
            f'<p><b>🎯 目标</b>：{esc(card.get("target"))}</p>'
            f'<p><b>🔧 动作</b>：{esc(card.get("action"))}</p>'
            f'<p><b>💰 费用</b>：{esc(card.get("cost"))}</p>'
            f'<p><b>✅ 成功标准</b>：{esc(card.get("success"))}</p>'
            f"</div>"
        )

    return f"""
<details class="deduce">
<summary>🧭 五步推演<span class="d-arrow">▼</span></summary>
<div class="d-body">
  <div class="d-step">
    <div class="d-step-title">① 破译信号：{signal_type}</div>
    <span class="d-signal">{signal_type}</span>
    <p>{signal}</p>
    <p style="color:var(--muted);font-size:12.5px;margin-top:4px">依据：{evidence}</p>
  </div>
  <div class="d-step">
    <div class="d-step-title">② 映射九域：最相关 → {top_industry}</div>
    {map_html}
  </div>
  <div class="d-step">
    <div class="d-step-title">③ 推演变革链</div>
    <p><b>成本：</b>{esc(d.get("cost_change"))}</p>
    <p><b>关系：</b>{esc(d.get("relation_change"))}</p>
    <p><b>机会：</b>{esc(d.get("opportunity"))}</p>
  </div>
  <div class="d-step">
    <div class="d-step-title">④ 定位象限：{quadrant}</div>
  </div>
  <div class="d-step">
    <div class="d-step-title">⑤ 落地阶梯</div>
    {stairs_html}
  </div>
  <div class="d-step">
    <div class="d-step-title">📇 顾问行动卡片</div>
    {card_html}
  </div>
</div>
</details>
"""


def _deduce_html(e: Dict) -> str:
    """渲染推演为可折叠区块；新结构（card）用顾问行动卡片，旧结构用五步推演；无数据返回空串"""
    d = e.get("deduce")
    if not isinstance(d, dict):
        return ""
    if isinstance(d.get("card"), dict):
        return _deduce_card_html(d)
    return _deduce_legacy_html(d)


def adv_nav_html(advice_cnt: Dict[str, int]) -> str:
    """生成侧栏"行动分级"导航（点击后页面只显示该分级新闻）。

    advice_cnt: {分级中文名: 条数}，如 {"立即行动": 3, ...}
    输出纯导航结构；样式在主 CSS，过滤脚本在页面脚本中。
    """
    chips = []
    total = 0
    for advice in _ADVICE_ORDER:
        n = advice_cnt.get(advice, 0)
        if not n:
            continue
        total += n
        title, _, cls, _ = _ADVICE_META[advice]
        chips.append(
            f'<a class="adv-chip {cls}" href="#adv-{cls}-1" data-cls="{cls}">{title}'
            f'<span class="adv-n">{n}</span></a>'
        )
    if not chips:
        return ""
    all_chip = (
        f'<a class="adv-chip adv-all" href="#adv-all" data-cls="all">📋 全部新闻'
        f'<span class="adv-n">{total}</span></a>'
    )
    return (
        '<nav class="adv-nav"><div class="adv-label">⚡ 行动分级</div>'
        + all_chip
        + "".join(chips)
        + "</nav>"
    )


def _entity_report_cards(entries: List[Dict], card_cls: str, adv_counter: Dict[str, int]) -> str:
    """渲染一组条目为卡片 HTML（洞察高亮，摘要弱化，五步推演可折叠）"""
    if not entries:
        return '<div class="empty">（无）</div>'

    cards = []
    for e in entries:
        score = e.get("score") or 0
        title = html.escape(e.get("title", "无标题"))
        link = e.get("link", "")
        source = html.escape(e.get("source", "未知"))
        insight = e.get("entity_insight") or ""
        summary = html.escape(e.get("summary", ""))
        tags = e.get("tags", []) or []
        industries = e.get("entity_industry", []) or []
        maturity = e.get("entity_maturity", "")
        effort = e.get("entity_effort", "")
        advice = e.get("entity_advice", "")

        title_html = (
            f'<a href="{html.escape(link, quote=True)}">{title}</a>'
            if link
            else title
        )
        insight_html = (
            f'<div class="insight"><span class="label">💡 实体洞察</span>'
            f"{html.escape(insight)}</div>"
            if insight
            else ""
        )
        summary_html = (
            f'<div class="summary">{summary}</div>' if summary else ""
        )
        industry_html = "".join(
            f'<span class="industry">{html.escape(str(x))}</span>' for x in industries
        )
        alternative_html = "".join(
            f'<span class="alternative">国产替代: {html.escape(str(x))}</span>'
            for x in (e.get("entity_alternative", []) or [])
        )
        badges = []
        if maturity:
            badges.append(f'<span class="badge maturity">{html.escape(maturity)}</span>')
        if effort:
            badges.append(f'<span class="badge effort">门槛 {html.escape(effort)}</span>')
        badge_html = "".join(badges)
        advice_cls = _ADVICE_CLS.get(advice, "watch")
        adv_counter[advice_cls] = adv_counter.get(advice_cls, 0) + 1
        adv_no = adv_counter[advice_cls]

        cards.append(
            f'<div class="card" id="adv-{advice_cls}-{adv_no}" data-adv="{advice_cls}">'
            f'<div class="card-top">'
            f'<span class="score {advice_cls}" title="行动分级">{_ADVICE_EMOJI[advice_cls]}</span>'
            f"<h3>{title_html}</h3>"
            f"</div>"
            f'<div class="meta-line">'
            f"{industry_html}{alternative_html}{badge_html}"
            f'<span class="badge advice {advice_cls}">{html.escape(advice)}</span>'
            f'<span style="margin-left:auto">{source}</span>'
            f"</div>"
            f"{insight_html}"
            f"{_deduce_html(e)}"
            f"{summary_html}"
            f"</div>"
        )
    return "\n".join(cards)


def render_entity_report(
    entries: List[Dict],
    config: Dict,
    date_str: str,
) -> str:
    """生成"AI Daily 实体洞察日报"HTML：按 AI 能力类型分组展示实体相关新闻。

    Args:
        entries: 评分后的条目（含 entity_relevant / entity_insight / category / 行业/成熟度/门槛/行动）
        config: 完整配置（读取 filter.hot_threshold / filter.min_score）
        date_str: 报告日期（YYYY-MM-DD）
    """
    min_score = config["filter"]["min_score"]

    relevant = [e for e in entries if e.get("entity_relevant", True)]
    qualified = [e for e in relevant if (e.get("score") or 0) >= min_score]
    irrelevant = len(entries) - len(relevant)

    # 按 AI 能力类型分组（组内按分数排序）
    cat_groups = {cat: [] for cat in _CATEGORY_ORDER}
    for e in qualified:
        cat = e.get("category", "")
        if cat not in cat_groups:
            cat = "其他"
        cat_groups[cat].append(e)
    for cat in _CATEGORY_ORDER:
        cat_groups[cat].sort(key=lambda x: x.get("score") or 0, reverse=True)

    # 分类导航条（含条数）
    nav_chips = []
    for i, cat in enumerate(_CATEGORY_ORDER):
        n = len(cat_groups[cat])
        if not n:
            continue
        title, _ = _CATEGORY_META[cat]
        nav_chips.append(
            f'<a class="cat-chip" href="#cat-{i}">{title}<span class="cat-n">{n}</span></a>'
        )
    nav_html = f'<nav class="cat-nav">{"".join(nav_chips)}</nav>' if nav_chips else ""

    # 行动分级统计（附在 hero + 侧栏导航）
    advice_cnt = {}
    for e in qualified:
        advice_cnt[e.get("entity_advice", "观望")] = advice_cnt.get(e.get("entity_advice", "观望"), 0) + 1
    advice_sum = " · ".join(
        f"{_ADVICE_META.get(a, (a,))[0]} {advice_cnt[a]}" for a in _ADVICE_ORDER if advice_cnt.get(a)
    )
    advice_sum_html = (
        f'<div class="advice-line">今日行动分级：{advice_sum}</div>' if advice_sum else ""
    )

    # 分类分组区块（卡片按行动分级顺序编号，用于侧栏分级锚点）
    adv_counter: Dict[str, int] = {"act": 0, "try": 0, "watch": 0, "skip": 0}
    sections = []
    for i, cat in enumerate(_CATEGORY_ORDER):
        group = cat_groups[cat]
        if not group:
            continue
        title, desc = _CATEGORY_META[cat]
        sections.append(
            f'<section id="cat-{i}" class="cat-group">'
            f'<h2 class="cat-title">{title}'
            f'<span class="cat-count">{len(group)} 条</span>'
            f'<span class="cat-desc">{desc}</span>'
            f"</h2>"
            f'<div class="cat-cards">'
            f"{_entity_report_cards(group, 'watch', adv_counter)}"
            f"</div>"
            f"</section>"
        )
    if not sections:
        sections.append('<div class="empty">当日无实体相关精选新闻</div>')
    body = "\n".join(sections)

    stats = (
        f'<div class="stats">'
        f'<div class="stat"><b>{len(qualified)}</b>实体精选</div>'
        f'<div class="stat"><b>{irrelevant}</b>与实体无关</div>'
        f"</div>"
    )

    title = "老许聊实体-AI×实体洞察日报"
    escaped_title = html.escape(title)
    h1_html = "老许聊实体-<span class=\"hl\">AI</span>×实体洞察日报"
    douyin_url = (
        "https://www.douyin.com/search/%E8%80%81%E8%AE%B8%E8%81%8A%E5%AE%9E%E4%BD%93"
    )
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{escaped_title}</title>
{_ENTITY_CSS}
</head>
<body>
<div class="page">
  <aside class="sidebar">
    <div class="brand">老许聊实体<span class="brand-sub">AI × 实体洞察日报</span></div>
    {nav_html}
    {adv_nav_html(advice_cnt)}
  </aside>
  <main class="main">
    <div class="hero">
      <h1>{h1_html}</h1>
      <div class="meta">{date_str} · AI × 实体商业动态 · 给实体经营者的行动指南</div>
      <div class="contact">
        <a href="{douyin_url}" target="_blank" rel="noopener">🎵 抖音 @老许聊实体</a>
        <span class="copy-wx" onclick="copyWx(this)">💬 微信 xuyang2946 <span class="tip">点击复制</span></span>
      </div>
      {advice_sum_html}
      {stats}
    </div>
    <div class="content">
{body}
    </div>
    <div class="footer">Generated by AI Daily</div>
  </main>
</div>
<script>
function copyWx(el){{
  var text = "xuyang2946";
  var tip = el.querySelector(".tip");
  var ok = function(){{
    if (tip){{ tip.textContent = "已复制 ✓"; setTimeout(function(){{ tip.textContent = "点击复制"; }}, 2000); }}
  }};
  var fail = function(){{ if (tip) tip.textContent = "复制失败，请手动添加"; }};
  if (navigator.clipboard && navigator.clipboard.writeText) {{
    navigator.clipboard.writeText(text).then(ok).catch(fail);
  }} else {{
    var ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    try {{ document.execCommand("copy"); ok(); }} catch (e) {{ fail(); }}
    document.body.removeChild(ta);
  }}
}}
(function(){{
  var chips = document.querySelectorAll(".cat-chip");
  function setActive(hash){{
    chips.forEach(function(c){{ c.classList.toggle("active", c.getAttribute("href") === hash); }});
  }}
  chips.forEach(function(c){{
    c.addEventListener("click", function(){{ setActive(c.getAttribute("href")); }});
  }});
  window.addEventListener("hashchange", function(){{ setActive(location.hash); }});
  setActive(location.hash);
}})();
(function(){{
  var chips = document.querySelectorAll(".adv-chip");
  var cards = document.querySelectorAll(".card[data-adv]");
  var groups = document.querySelectorAll(".cat-group");
  function apply(cls){{
    cards.forEach(function(c){{ c.style.display = (cls === "all" || c.getAttribute("data-adv") === cls) ? "" : "none"; }});
    groups.forEach(function(s){{
      var any = false;
      s.querySelectorAll(".card").forEach(function(c){{ if (c.style.display !== "none") any = true; }});
      s.style.display = any ? "" : "none";
    }});
  }}
  chips.forEach(function(c){{
    c.addEventListener("click", function(){{
      chips.forEach(function(x){{ x.classList.toggle("active", x === c); }});
      apply(c.getAttribute("data-cls"));
      window.scrollTo({{ top: 0, behavior: "smooth" }});
    }});
  }});
  apply("all");
  chips.forEach(function(c){{ c.classList.toggle("active", c.getAttribute("data-cls") === "all"); }});
}})();
</script>
</body>
</html>
"""


def save_entity_report(
    entries: List[Dict],
    config: Dict,
    date_str: str,
    data_dir: str = "news-data",
) -> str:
    """生成并保存实体洞察日报 HTML 到 data_dir/daily-{date}.html。

    Returns:
        生成的 HTML 文件路径
    """
    from pathlib import Path

    html_page = render_entity_report(entries, config, date_str)
    path = Path(data_dir) / f"daily-{date_str}.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html_page, encoding="utf-8")
    print(f"📊 实体洞察日报已生成: {path}")
    return str(path)
